import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "./_Components/navbar/page";
import Footer from "./_Components/footer/page";
import toast, { Toaster } from 'react-hot-toast';
import CartContextProvider from "./_Components/context/cartContext";
import WishContextProvider from "./_Components/context/wishlistContext";
import { SessionProvider } from "next-auth/react";
import MySessionProvider from "./_Components/MySessionProvider/MySessionProvider";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "E-commerce App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       <MySessionProvider>

        
        <CartContextProvider>
          <WishContextProvider>
          <Nav />  
        <div className="container mx-auto">
          {children}
          <Toaster />
        </div>
        <Footer></Footer>
        </WishContextProvider>
       </CartContextProvider>

       </MySessionProvider>
     
      </body>
    </html>
  );
}
